config/routes.rb
NewsStoryFinder::Application.routes.draw do
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
    controllers: { omniauth_callbacks: :omniauth_callbacks }

  resources :stories
  resources :categories

  get 'static_pages/home'
  get 'static_pages/welcome'

  root to: 'stories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :stories
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :category_id, :description, :title, :user_id
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  validates_presence_of :username
  validates_uniqueness_of :username
  has_many :stories

  def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.username = auth.info.nickname
  end
end

def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
end

def password_required?
  super && provider.blank?
end

def email_required?
	super && provider.blank?
end


def update_with_password(params, *options)
  if encrypted_password.blank?
    update_attributes(params, *options)
  else
    super
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, except: [:welcome]
  def home
  end

  def welcome
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @categories = Category.all
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])
    @story.user_id = current_user.id
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_path }
        format.json { render json: @story, status: :created, location: @story }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def flash_class(type)
			case type
			when :alert
				"alert-error"
			when :notice
				"alert-success"
			else
				""
			end
		end	
	end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsStoryFinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	    	<a href="#" class="brand">NewsStoryFinder</a>
	    	<ul class="navv nav pull-left divider-vertical">
	    		<li><%= link_to "Panama City Florida", root_path %></li>
	    	</ul>
	    	<ul class="nav pull-right">
	    		<% if user_signed_in? %>
	    		  <li class="divider-vertical"><%= link_to current_user.username, static_pages_home_path %></li>	
				  <li class="divider-vertical"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				<% else %>
				  <li class="divider-vertical"><%= link_to "Sign up", new_user_registration_path %></li>
				  <li class="divider-vertical"><%= link_to "Login", new_user_session_path %></li>
				  <li class="divider-vertical"><%= link_to image_tag('sign-in-with-twitter-gray.png'), user_omniauth_authorize_path(:twitter) %></li>
				<% end %>
	    	</ul>
	    </div>
	   </div>
	 </div>

	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
				</div>
		<% end %>		
			
<%= yield %>
	

</body>
</html>

app/views/static_pages/home.html.erb
<p id="notice"><%= notice %></p>
<div class="header">
	<h3><%= current_user.username %> Story's</h3>
</div>

<% current_user.stories.each do |story| %>
<div class="well well-small">
<strong><%= story.title %></strong> |
<%= link_to time_ago_in_words(story.created_at) + " ago", story %><br />
<%= link_to 'Edit', edit_story_path(story), params: :id %> |
<%= link_to 'Remove', story, method: :delete, data: { confirm: 'Are you sure?' } %> 
</div>
<% end %>
<h5><%= link_to "Edit Your Account", edit_user_registration_path %></h5>

app/views/static_pages/welcome.html.erb
<h1>StaticPages#welcome</h1>
<p>Find me in app/views/static_pages/welcome.html.erb</p>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= collection_select(:story, :category_id, @categories, :id, :name, {:prompt => false })  %><br />
   <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<div class="well well-large">
  <div class="row">
    <h1 class="span8">Story Ideas</h1>
    <a><%= link_to "Submit a News Story Idea", new_story_path, class: "btn btn-info span2" %></a>
  </div>
</div>
<div>
  <h5>Category</h5>
</div>
<% @stories.each do |story| %>
<div class="well well-small">
<div class="status">
  <div class="row">
    <div class="span2">
      <p><%= story.category.name %></P>
      </div>
    <div class="span7">
      <strong><%= story.title %></strong>
      <p><%= story.description %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(story.created_at) + " ago", story %>
    </div>
    </div>
  </div>
 </div> 
</div>
<% end %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<h4>Your Story</h4>
<div class="well">
<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>Description:</b>
  <%= @story.description %>
</p>

<p>
  <b>Category:</b>
  <%= @story.category.name %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>
</div>